# Generated by Django 5.1 on 2024-10-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_subject', models.CharField(max_length=200)),
                ('contact_message', models.TextField(max_length=1000)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('contact_actioned', models.BooleanField(default=False)),
            ],
        ),
    ]
