# Generated by Django 5.1 on 2024-09-08 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('format_type', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.CharField(blank=True, max_length=254, null=True)),
                ('publisher', models.CharField(blank=True, max_length=254, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('edition', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('num_of_pages', models.IntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=254, null=True)),
                ('is_favourite', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
    ]
