# Generated by Django 5.1 on 2024-09-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='language',
        ),
    ]
